### ISSUE TITLE
Create v0.8.0 tag

### ISSUE THREAD

**Issue by MikeGoldsmith** [open-telemetry/opentelemetry-proto-go#10]
#9 updated the repo to v.0.8.0 of the proto files we now need to tag the repo so it's available.

**Comment by MikeGoldsmith** [comment]
Again, happy to help manage this project.

@tigrannajaryan @bogdandrutu @MrAlias - I'm not sure who has write-access to this repo and it doesn't codeowners to auto-assign.

**Comment by tigrannajaryan** [comment]
@MikeGoldsmith do we just need a v0.8.0 tag? Anything else needed (I am not familiar with the release process for this repo).

**Comment by MrAlias** [comment]
Yeah, I think a tag is all we need (this is the thing that pushes the go pkg), but I'm going to make a related GitHub release as well.

**Comment by MrAlias** [comment]
https://github.com/open-telemetry/opentelemetry-proto-go/releases/tag/v0.8.0

**Comment by MrAlias** [comment]
@MikeGoldsmith I created https://github.com/open-telemetry/community/issues/720 to add teams to manage this repo, PTAL.

**Comment by MikeGoldsmith** [comment]
Great, thanks @MrAlias @tigrannajaryan 👍🏻
