### ISSUE TITLE
JSON unmarshal of metrics/v1.MetricsData doesn't work

### ISSUE THREAD

**Issue by swamisriman** [open-telemetry/opentelemetry-proto-go#176]
```
jsonString := "<json string>"
var metricsData v1.MetricsData
_ = json.Unmarshal([]byte(jsonString), &metricsData)

fmt.Println(metricsData.String())

```

The above code gives empty output. ie; JSON unmarshal is not working.
I gave [this file](https://github.com/open-telemetry/opentelemetry-proto/blob/main/examples/metrics.json) contents as `jsonString`

Are we not supposed to be unmarshalling the json into this data type?

**Comment by dmathieu** [comment]
This JSON document seems wrong:

https://github.com/open-telemetry/opentelemetry-proto-go/blob/4ef95d5874c17988208c790494008b35b0d45d89/otlp/metrics/v1/metrics.pb.go#L229

The resource metrics key should be `resource_metrics`, it's `resourceMetrics`.

And the collector's generated structs are the same. So it's an example issue, not one with the generated code.
https://github.com/open-telemetry/opentelemetry-collector/blob/eaab76e46d3849bfe5ece1f53155877b128283c8/pdata/internal/data/protogen/metrics/v1/metrics.pb.go#L175

**Comment by swamisriman** [comment]
@dmathieu 
So, the issue is that the example [metrics.json](https://github.com/open-telemetry/opentelemetry-proto/blob/main/examples/metrics.json) is wrong? 
If so, I'll take this issue over there

**Comment by swamisriman** [comment]
@dmathieu 
I tried changing the `resourceMetrics` to `resource_metrics` and `scopeMetrics` to `scope_metrics`
and tried the following input
```
{
  "resource_metrics": [
    {
      "scope_metrics": [
        {
          "metrics": [
            {
              "name": "my.counter",
              "unit": "1",
              "description": "I am a Counter",
              "sum": {
                "aggregation_temporality": 1
              }
            }
          ]
        }
      ]
    }
  ]
}
```
This is the output I got
`resource_metrics:{scope_metrics:{metrics:{name:"my.counter" description:"I am a Counter" unit:"1"}}}`

The metric types like `sum`, `gauge` and `histogram` are not being parsed.
Is that because the `json:"..."` entry is missing here?
https://github.com/open-telemetry/opentelemetry-proto-go/blob/4ef95d5874c17988208c790494008b35b0d45d89/otlp/metrics/v1/metrics.pb.go#L522

**Comment by swamisriman** [comment]
**Update:**
I tried marshalling the below data
```
        sum := v1.Sum{
		AggregationTemporality: 1,
		IsMonotonic:            true,
	}
	metric_sum := v1.Metric_Sum{
		Sum: &sum,
	}
	metric := v1.Metric{
		Name: "my.sum",
		Data: &metric_sum,
	}
	metrics := []*v1.Metric{&metric}
	scopeMetric := v1.ScopeMetrics{
		Metrics: metrics,
	}
	scopeMetrics := []*v1.ScopeMetrics{&scopeMetric}
	resourceMetric := v1.ResourceMetrics{
		ScopeMetrics: scopeMetrics,
	}
	resourceMetrics := []*v1.ResourceMetrics{&resourceMetric}
	metricsData := v1.MetricsData{
		ResourceMetrics: resourceMetrics,
	}
	
	jsonBytes, _ := json.Marshal(metricsData)
	fmt.Println(string(jsonBytes))
```
This is the json string I got (formatted version of it)
```
{
  "resource_metrics": [
    {
      "scope_metrics": [
        {
          "metrics": [
            {
              "name": "my.sum",
              "Data": {
                "Sum": {
                  "aggregation_temporality": 1,
                  "is_monotonic": true
                }
              }
            }
          ]
        }
      ]
    }
  ]
}
```

When I try to unmarshall the same string back to v1.MetricsData, I got this error
```
json: cannot unmarshal object into Go struct field Metric.resource_metrics.scope_metrics.metrics.Data of type v1.isMetric_Data
```

**Comment by swamisriman** [comment]
@dmathieu / @MrAlias 

I see that this issue is assigned to me.
Is it because you are waiting for me to raise this in the [opentelemetry-proto](https://github.com/open-telemetry/opentelemetry-proto) repo?

Also please check my last 2 comments. There seems to be an issue with metric type parsing.

**Comment by dmathieu** [comment]
This seems to be because metrics data is a `oneof`, which is generated as an interface.
See https://github.com/golang/protobuf/issues/256

Within your project, you should possibly try generating the code with https://github.com/mitchellh/protoc-gen-go-json

**Comment by swamisriman** [comment]
Ok, so I understand that there is a limitation with JSON parsing when the proto template contains `oneof`.
Got it.

I raised an [issue in the proto repo](https://github.com/open-telemetry/opentelemetry-proto/issues/565) for incorrect key cases in the examples

Thanks for looking into this guys.

**Comment by tigrannajaryan** [comment]
The [spec says](https://github.com/open-telemetry/opentelemetry-proto/blob/main/docs/specification.md#json-protobuf-encoding):

>The keys of JSON objects are **field names converted to lowerCamelCase**. Original field names are not valid to use as keys for JSON objects. For example, this is a valid JSON representation of a Resource: { "attributes": {...}, "droppedAttributesCount": 123 }, and this is NOT a valid representation: { "attributes": {...}, "dropped_attributes_count": 123 }.

Looks like implementation is wrong.

**Comment by swamisriman** [comment]
@dmathieu
According to spec shared by Tigran, the examples comply with the spec and we should be using camel case.
Any comments?

**Comment by dmathieu** [comment]
I think this is something that has to be fixed within the proto repository.
This repository only generates code from the protobuf definitions.

**Comment by swamisriman** [comment]
I went through the [protobuf docs for JSON](https://protobuf.dev/programming-guides/proto3/#json)
> Message field names are mapped to lowerCamelCase and become JSON object keys

So, when .pb.go file is generated by protoc, protoc is supposed to use lowerCamelCase in struct tag (unless we override it using `json_name`, which we didn't).
Instead, it generated code with snake_case.
https://github.com/open-telemetry/opentelemetry-proto-go/blob/4ef95d5874c17988208c790494008b35b0d45d89/otlp/metrics/v1/metrics.pb.go#L229
So, something's wrong with Go protoc.

@dmathieu, does this sound correct?

**Comment by dmathieu** [comment]
I think the solution here may be to use protojson to marshal/unmarshal data rather than the json package.
https://pkg.go.dev/google.golang.org/protobuf/encoding/protojson

**Comment by swamisriman** [comment]
Yeah @dmathieu 

I too just found that we are not supposed to be using standard `encoding/json` package and we should be using `protojson` package
https://github.com/golang/protobuf/issues/183#issuecomment-218583981
> I don't think there's anything to do. You need to use jsonpb. The field names are only the first point of divergence. There's several other parts of the proto3 JSON spec that make it impossible to use the standard encoding/json package, like WKTs.

So, `encoding/json` looks at `json` tag
and `protojson` looks at `protobuf.json` tag, which is in compliance with [proto spec](https://protobuf.dev/programming-guides/proto3/#json) and obeys `json_name`

When I use `protojson`, everything works fine.

Thanks for your time!!
