### ISSUE TITLE
Please export `isAnyValue_Value`

### ISSUE THREAD

**Issue by kentquirk** [open-telemetry/opentelemetry-proto-go#25]
The AnyValue struct contains this:
``` 
type AnyValue struct {
...
	Value isAnyValue_Value `protobuf_oneof:"value"`
}
```

This is an exported member of the struct, but its type is not exported.

This means that it is literally impossible for an application that wants to construct values to write a function that returns one of these.  You can't say:

```
var av AnyValue
av.Value = file.ReadValue()
```

In my particular case, I want to write a parser that can generate a variety of Value types. The parser should be able to return both Int and Double versions of values. It simply can't. 

I believe that it would be a non-breaking change to export this type, and I also think it's really unfriendly to API users to have to work with exported values of unexported types. Any chance of fixing it, please?

If a PR is the best way to handle it, please say so and I'll create one. I figured it would be best to ask first.

**Comment by tigrannajaryan** [comment]
This is autogenerated code and cannot be altered. It is generated by Protobuf compiler. I agree it is an unnecessary limitation but there is nothing we can do here. You may want to file it as an issue with Protobuf folks.
