### ISSUE TITLE
Define an initial rollout strategy

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-proto-go#3]
Based on the resolution of #2 there should be tooling to generate Go source code from the proto source.

We need to define and document our strategy and steps for generating the Go source and publishing it. From there we can perform the procedure.

## Open Questions

How do we want to provide different versions of the proto source as Go source?

Should we provide Go source for old version of the proto?

**Comment by MadVikingGod** [comment]
I'm sorry I'm doing this from my phone, I'll edit when I get back to a computer, but I got to get it out of my head.

I think we should add three goals to the readme of this repo.
- Compatibility with go versioning over tracking otlp version number
- an easy and discoverable way to match go version to otlp version
- only update on new releases to otlp

With those goals in mind here are my suggestions.
1. Until otlp releases a version that doesn't work with go's versioning we just follow otlp version
   - this means that the trace API will be unstable until otlp makes a v1 release.
   - when otlp makes a release this is incompatible we will have to change our versioning, this is a one way door in most cases (see below)
2. When we move to a non-tracked version system we should recognize this is a one way door, and it would take a stable v2 semver version of otlp to go back to tracked.
    - we should add guidelines like minimize number of mods, or symmetry in mods; and no stable depending on unstable
    - consistent versioning will be hard, we will need something like goreleaser to make it work

As for should we do old versions, nothing until there is a demonstrated need. No code right now can depend on this code, and an old version of otlp. There is a good argument if they are going to move to use this library, then they should at least use this version or newer. But, if there is a use case, I don't see why someone couldn't contribute those versions.

**Comment by MrAlias** [comment]
Stale: we are rolled out.
