### ISSUE TITLE
Using this package as a golang module

### ISSUE THREAD

**Issue by jacobmarble** [open-telemetry/opentelemetry-proto-go#8]
In order to import this package as suggested with `import tracepb "go.opentelemetry.io/proto/otlp/trace/v1"`, the importing package seems to require a replace directive:
```
require (
	...
	go.opentelemetry.io/proto/otlp v0.7.0
	...
)

replace go.opentelemetry.io/proto/otlp => github.com/open-telemetry/opentelemetry-proto-go/otlp v0.7.0
```

**Comment by MrAlias** [comment]
We are still in the process of setting up the vanity URL for this repository.

**Comment by jacobmarble** [comment]
Cool.

By the way, I'm very happy to have this repository. So much easier than setting up the generation myself. Thanks!

**Comment by MadVikingGod** [comment]
@jacobmarble The vanity URL is now working, do you still need the replace?

**Comment by jacobmarble** [comment]
Thank you, this is working without `replace` now.

Have a great week!
